-- LuaFormatter off
local disabled = {
    'agda',
    'astro',
    -- 'bash',
    'beancount',
    'bibtex',
    'c',
    'c_sharp',
    'clojure',
    -- 'cmake',
    -- 'comment',
    'commonlisp',
    'cooklang',
    'cpp',
    -- 'css',
    'cuda',
    'd',
    'dart',
    'devicetree',
    -- 'diff',
    -- 'dockerfile',
    'dot',
    'eex',
    'elixir',
    'elm',
    'elvish',
    'embedded_template',
    'erlang',
    'fennel',
    'fish',
    'foam',
    'fortran',
    'fusion',
    'gdscript',
    -- 'git_rebase',
    -- 'gitattributes',
    -- 'gitignore',
    'gleam',
    'glimmer',
    'glsl',
    -- 'go',
    'gdresource',
    -- 'gomod',
    -- 'gowork',
    'graphql',
    'hack',
    'haskell',
    -- 'hcl',
    'heex',
    -- 'help',
    -- 'hjson',
    'hlsl',
    'hocon',
    -- 'html',
    -- 'http',
    -- 'java',
    -- 'javascript',
    -- 'jsdoc',
    -- 'json',
    -- 'json5',
    -- 'jsonc',
    -- 'jsonnet',
    'julia',
    'kotlin',
    'lalrpop',
    'latex',
    'ledger',
    -- 'llvm',
    -- 'lua',
    'm68k',
    -- 'make',
    -- 'markdown',
    -- 'markdown_inline',
    'menhir',
    -- 'meson',
    'nickel',
    -- 'ninja',
    -- 'nix',
    'norg',
    'ocaml',
    'ocaml_interface',
    'ocamllex',
    'pascal',
    -- 'perl',
    -- 'php',
    -- 'phpdoc',
    'pioasm',
    -- 'proto',
    'pug',
    -- 'python',
    -- 'ql',
    'qmljs',
    -- 'query', -- Tree-sitter query language
    'r',
    'racket',
    'rasi',
    -- 'regex',
    'rego',
    -- 'rst',
    'ruby',
    -- 'rust',
    'scala',
    -- 'scheme',
    -- 'scss',
    'slint',
    'solidity',
    'sparql',
    -- 'sql',
    'supercollider',
    'surface',
    'svelte',
    'swift',
    'sxhkdrc',
    'teal',
    'tiger',
    'tlaplus',
    -- 'todotxt',
    -- 'toml',
    'tsx',
    'turtle',
    -- 'typescript',
    'v',
    'vala',
    'verilog',
    'vhs',
    -- 'vim',
    -- 'vue',
    'wgsl',
    -- 'yaml',
    'yang',
    -- 'zig',
}
-- LuaFormatter on

require('nvim-treesitter.configs').setup {
    ensure_installed = 'all',
    -- sync_install = true,
    ignore_install = disabled,
    indent = {
        enable = true
    },
    highlight = {
        enable = true,
        disable = disabled
    },
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = true,
    -- playground = {
    --     enable = true,
    --     disable = disabled,
    --     updatetime = 25,
    --     persist_queries = false
    -- },
    -- incremental_selection = {
    --     enable = true,
    --     keymaps = {
    --         init_selection = '<Leader>)',
    --         node_incremental = ')',
    --         node_decremental = '('
    --     }
    -- }
}
